[package]
name = "rustabase"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
pest = "2.8.3"
pest_ascii_tree = "0.1.0"
pest_derive = "2.8.3"
thiserror = "2.0.17"
