[package]
name = "project2"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
bevy = { version = "0.17.3", features = ["track_location", "mp3"] }
bevy_egui = "0.38.1"
noise = "0.9.0"
rand = "0.9.2"
serde = "1.0.228"
serde_json = "1.0.149"
serde_with = "3.16.1"
